"""
Create lesion shape.
"""

from __future__ import annotations

__all__ = [
    "get_bottom_of_sulci",
    "grow_random_lesion",
]

import heapq
from typing import Any, cast

import numpy as np
from scipy import ndimage
from scipy.spatial import ConvexHull

from synthfcd.core.masks import get_binary_mask
from synthfcd.core.utils import (
    generate_noise_field,
    get_hemisphere_at_point,
    postprocess_mask,
)
from synthfcd.utils._aliases import (
    _DistanceType,
    _GrowTargetResultType,
    _GrowthModeType,
    _LabelEnumType,
    _LobeType,
    _RNGType,
)
from synthfcd.utils._base import _LabelEnum
from synthfcd.utils._const import (
    GROW_LESION_MASK_THRES,
    GROW_LESION_NOISE_LAMBDA,
    SEED_OFFSET_GROWTH,
)
from synthfcd.utils._validators import (
    IntNoBool,
    RealNoBool,
    validate_3d_numpy_array,
    validate_class_type,
    validate_literal_str,
    validate_obj_type,
    validate_spacing,
)
from synthfcd.utils.misc import get_rng
from synthfcd.utils.seg_labels import SynthSegLabel


def grow_random_lesion(
    seg_mask: np.ndarray,
    spacing: tuple[_DistanceType, _DistanceType, _DistanceType],
    *,
    volume: _DistanceType,
    gm_prob: float = 0.5,
    growth: _GrowthModeType = "distance",
    lobe: _LobeType | None = None,
    bottom_of_sulcus: bool = False,
    fast_mode: bool = True,
    distance_noise_ratio: float = GROW_LESION_NOISE_LAMBDA,
    skip_postprocess: bool = False,
    attempt_no: int = 0,
    max_attempts: int = 10,
    random_seed: int | None = None,
    random_state: _RNGType | None = None,
    label_enum: _LabelEnumType = SynthSegLabel,
    **kwargs,
) -> _GrowTargetResultType:
    """
    Generate a synthetic lesion mask by stochastically growing a connected region from a
    randomly selected seed voxel in the GM-WM boundary.

    Lesion growth occurs using two methods:
    - ``'distance'``: growth is driven by minimizing the Euclidean distance to
        the seed point for the target volume. Shape variability is ensured by
        a noise field that disturbs the distances, a parameter that controls
        expansion toward the GM or WM (``gm_prob``), as well as the anatomy
        of the seed region. This method inherently produces more isotropic; i.e.,
        spherical shapes when ``gm_prob`` is 0.5.
    - ``'irregular'``: growth is driven by 'contaminating' neighboring voxels
        without at any possible direction. Similarly, `gm_prob` and brain anatomy
        control the lesion morphology. This method produces more irregular shapes.

    Users can limit the selection of seed points to a specific lobe or the bottom of
    the sulcus by setting the ``lobe`` and ``bottom_sulcus`` parameters.

    Notes:
        If the generated lesion does not reach the requested volume, the process is
            retried recursively up to ``max_attempts``.
        Both approaches can handle any isotropic or anisotropic spacing. For higher
            anisotropy, the ``'distance'`` method yields more anatomically plausible
            results. The ``fast_mode`` flag can be used to slightly speed up (~2x) the
            process in the ``'irregular'`` method with anisotropic spacing, at the
            cost of slightly reduced robustness to anisotropy.
        For isotropic 1mm^3 skull-stripped image the algorithm completes in <0.5s.

    Args:
        seg_mask (np.ndarray):
            The segmentation mask that guides the anatomically-grounded lesion growth,
            generated by `synthfcd.core.masks.generate_seg_mask`.
        spacing (tuple[float | int, float | int, float | int], optional):
            The voxel spacing of the segmentation mask in mm.
        volume (int | float):
            The target volume for the lesion in physical units (mm^3).
        gm_prob (float):
            Probability that a sampled voxel is allowed to grow into gray matter.
        growth (Literal["irregular", "isotropic"], optional):
            The growth mode to use for lesion growth. Supported values are:
            ``"irregular"`` (default) or ``"isotropic"``.
        lobe (list[int] | set[int] | int | None, optional):
            The lobe(s) to extract the masks for. Defaults to None.
        bottom_of_sulcus (bool, optional):
            Whether to filter the lesion growth to the bottom of the sulcus.
            Defaults to ``False``.
        fast_mode (bool, optional):
            Whether to use the fast mode for irregular growth. Defaults to ``True``.
            Has no effect if spacing is isotropic. Results to approx. 2x speedup.
        distance_noise_ratio (float, optional):
            Noise modulation parameter for distance-based growth. Determines the degree
            of irregularity in the lesion shape. Defaults to 0.3 after empirical tuning.
        skip_postprocess (bool, optional):
            Whether to skip the postprocessing step. Defaults to ``False``.
        attempt_no (int, optional):
            The current recursive attempt index. Primarily internal.
            Defaults to ``0``.
        max_attempts (int, optional):
            Maximum number of attempts allowed to generate a lesion that meets
            the target volume. Defaults to ``10``.
        random_seed (int | None, optional):
            Random seed used to generate a random number generator. If ``None``, a
            default random number generator is used.
        random_state (np.random.RandomState | np.random.Generator | None, optional):
            The random number generator to use. If ``None``, a default random number
            generator is used. If both ``random_seed`` and ``random_state`` are provided,
            ``random_state`` is prioritized.
        label_enum (type[LabelEnum], optional):
            The label enumeration to use for reading ``seg_mask``.
            Defaults to ``synthfcd.utils.SynthSegLabel``.

    Returns:
        dict[str, Any]:
            A dictionary containing the following keys:
            - ``"lesion_mask"``: A binary lesion mask (same shape as the input masks)
            - ``"growth_stats"``: A dictionary describing resulting lesion growth statistics.

    Raises:
        ValueError:
            If required mask keys are missing or empty, mask shapes are incompatible, or
            the lesion type is invalid.
        ValueError:
            If no valid seed voxel can be selected.
        RuntimeError:
            If a valid lesion cannot be generated after ``max_attempts`` attempts.
    """
    validate_3d_numpy_array(seg_mask, "seg_mask", dtype=np.integer)
    gm_mask = get_binary_mask(seg_mask, mask_type="gm", label_enum=label_enum)
    wm_mask = get_binary_mask(seg_mask, mask_type="wm", label_enum=label_enum)
    if not gm_mask.any() or not wm_mask.any():
        raise ValueError(
            "`gm_mask` or `wm_mask` are empty; cannot infer location of lesion growth"
        )

    validate_spacing(spacing, "spacing")

    validate_obj_type(lobe, "lobe", (IntNoBool, list, set, type(None)))
    cortical_labels = label_enum.get_cortical_labels()
    if isinstance(lobe, (list, set)):
        if not all(isinstance(l, IntNoBool) for l in lobe):
            raise ValueError("`lobe` list must contain only integers")
        if not all(l in cortical_labels for l in lobe):
            raise ValueError("`lobe` list must contain only cortical labels")
    elif lobe is not None:
        if lobe not in cortical_labels:
            raise ValueError(f"`lobe` must be a cortical label; got {lobe}")
        lobe = [lobe]

    validate_obj_type(bottom_of_sulcus, "bottom_of_sulcus", bool)

    validate_literal_str(
        growth,
        name="growth",
        target_literals=("irregular", "distance"),
    )

    validate_obj_type(volume, "volume", RealNoBool)
    if float(volume) <= 0.0:
        raise ValueError("`volume` must be greater than 0")

    validate_obj_type(gm_prob, "gm_prob", RealNoBool)
    if float(gm_prob) < 0.0 or float(gm_prob) > 1.0:
        raise ValueError("`gm_prob` must be between 0 and 1")

    validate_obj_type(distance_noise_ratio, "distance_noise_ratio", RealNoBool)
    if float(distance_noise_ratio) < 0.0 or float(distance_noise_ratio) > 1.0:
        raise ValueError("`distance_noise_ratio` must be between 0 and 1")

    validate_obj_type(skip_postprocess, "skip_postprocess", bool)
    validate_obj_type(attempt_no, "attempt_no", IntNoBool)
    validate_obj_type(max_attempts, "max_attempts", IntNoBool)
    if attempt_no < 0:
        raise ValueError("`attempt_no` must be greater than or equal to 0")
    if max_attempts <= 0:
        raise ValueError("`max_attempts` must be greater than 0")
    if attempt_no >= max_attempts:
        raise RuntimeError(
            f"Failed to generate lesion; number of attempts reached `max_attempts`: {max_attempts}."
        )

    validate_obj_type(fast_mode, "fast_mode", bool)
    validate_class_type(label_enum, "label_enum", _LabelEnum)

    # Setup; get random state and data
    rng = get_rng(
        seed=random_seed, random_state=random_state, offset=SEED_OFFSET_GROWTH
    )

    # Initial pool of candidate seeds underneath the GM-WM boundary (inside GM)
    candidates_mask = ndimage.binary_dilation(wm_mask, iterations=1) & gm_mask

    # Filter by lobe
    if lobe is not None:
        candidates_mask &= np.isin(seg_mask, list(lobe))
        if not candidates_mask.any():
            raise RuntimeError(
                "No candidate seed points found in lobe; loosen `lobe` or check segmentation masks."
            )

    # Additional filtering for bottom of sulcus
    if bottom_of_sulcus:
        candidates_mask &= get_bottom_of_sulci(
            shape=seg_mask.shape,
            candidates_mask=candidates_mask,
            wm_mask=wm_mask,
            spacing=spacing,
        )
        if not candidates_mask.any():
            raise RuntimeError(
                "No candidate seed points found in bottom of sulcus following lobe filtering; "
                "disable `bottom_of_sulcus` or check segmentation masks."
            )

    # Ensure candidates lie in a hemisphere
    lateralized = label_enum.get_all_labels(
        hemisphere="left"
    ) | label_enum.get_all_labels(hemisphere="right")
    candidates_mask &= np.isin(seg_mask, list(lateralized))
    if not candidates_mask.any():
        bottom_of_sulcus_str = " and bottom of sulcus" if bottom_of_sulcus else ""
        raise RuntimeError(
            f"No candidate seed points found in a hemisphere following lobe{bottom_of_sulcus_str} "
            "filtering; check segmentation masks."
        )

    # Randomly select a seed point
    candidate_seeds = np.argwhere(candidates_mask)
    seed_idx = rng.choice(range(len(candidate_seeds)))
    seed_point = tuple[Any, ...](candidate_seeds[seed_idx])
    if not gm_mask[*seed_point] and not wm_mask[*seed_point]:
        raise RuntimeError(
            "Seed point is not in GM or WM mask. Check ``gm_mask`` and ``wm_mask``."
        )

    hemisphere = get_hemisphere_at_point(seg_mask, seed_point, label_enum=label_enum)

    # Recompute gm_mask and wm_mask based on hemisphere
    gm_mask = get_binary_mask(
        seg_mask=seg_mask,
        mask_type="gm",
        hemisphere=hemisphere,
        label_enum=label_enum,
    )
    wm_mask = get_binary_mask(
        seg_mask=seg_mask,
        mask_type="wm",
        hemisphere=hemisphere,
        label_enum=label_enum,
    )

    # Initialize mask and totals
    lesion_mask = np.zeros(seg_mask.shape, dtype=bool)
    totals: dict[str, np.floating] = {
        "curr_volume": np.float32(0.0),
        "curr_gm_volume": np.float32(0.0),
    }

    if growth == "distance":
        success = _distance_based_growth(
            seed_point=seed_point,
            lesion_mask=lesion_mask,
            spacing=spacing,
            totals=totals,
            gm_mask=gm_mask,
            wm_mask=wm_mask,
            gm_prob=gm_prob,
            target_volume=volume,
            noise_lambda=distance_noise_ratio,
            rng=rng,
        )
    elif growth == "irregular":
        success = _irregular_growth(
            seed_point=seed_point,
            lesion_mask=lesion_mask,
            spacing=spacing,
            totals=totals,
            gm_mask=gm_mask,
            wm_mask=wm_mask,
            gm_prob=gm_prob,
            target_volume=volume,
            fast_mode=fast_mode,
            rng=rng,
        )

    # Retry if growth failed up to `max_attempts` times
    if not success:
        return grow_random_lesion(
            seg_mask=seg_mask,
            spacing=spacing,
            volume=volume,
            gm_prob=gm_prob,
            lobe=lobe,
            bottom_of_sulcus=bottom_of_sulcus,
            growth=growth,
            fast_mode=fast_mode,
            skip_postprocess=skip_postprocess,
            distance_noise_ratio=distance_noise_ratio,
            attempt_no=attempt_no + 1,
            max_attempts=max_attempts,
            random_seed=None,
            random_state=rng,
            label_enum=label_enum,
        )

    # Post-process lesion mask
    if not skip_postprocess:
        lesion_mask = postprocess_mask(
            mask=lesion_mask,
            spacing=spacing,
            smooth_sigma="auto",
            fill_holes=True,
            limit_to=gm_mask | wm_mask,
            keep_largest_component=True,
            threshold=GROW_LESION_MASK_THRES,
        )

    # Get lesion growth metadata
    volume = float(np.sum(lesion_mask) * np.prod(spacing))
    dkt_labels = [
        label_enum(int(l)).readable_name
        for l in np.unique(seg_mask[lesion_mask])
        if l in cortical_labels
    ]

    return {
        "target": lesion_mask,
        "growth_stats": {
            "volume": volume,
            "hemisphere": hemisphere,
            "DKT_labels": dkt_labels,
        },
    }


def get_bottom_of_sulci(
    shape: tuple[int, int, int],
    candidates_mask: np.ndarray,
    wm_mask: np.ndarray,
    spacing: tuple[_DistanceType, _DistanceType, _DistanceType],
) -> np.ndarray:
    """
    Get a mask of points from the bottom of a sulcus.

    Computes the disctance from the convex hull surface to the gray-white matter
    boundary, and finds points with the lowest laplacian (folding points) and
    highest depth (deepest points).

    TODO: polish for public usage.

    Note:
        The algorithm is biased towards the medial-posterior and inferior frontal lobe,
        as they exhibit higher depth and likely lower laplacian values. We recommend
        users first filter the candidate seeds by specific lobes to avoid such biases.

    Args:
        shape (tuple[int, int, int]):
            The shape of the masks in voxels.
        candidates_mask (np.ndarray):
            The candidate GM-WM boundary seed points.
        wm_mask (np.ndarray):
            The WM mask.
        spacing (tuple[float | int, float | int, float | int]):
            The spacing of the masks in mm.

    Returns:
        np.ndarray: The mask of points in the bottom of a sulcus.

    Raises:
        RuntimeError: If no vertices are found in the convex hull of the white matter.
    """
    oversample = 20  # smoothens the hull surface; empirically determined

    # Compute convex hull around WM
    wm_points = np.argwhere(wm_mask)
    hull = ConvexHull(wm_points)
    if len(hull.simplices) == 0:
        raise RuntimeError(
            "No triangles found in convex hull of white matter; "
            "try a different white matter mask."
        )

    # Get hull mask from vertices
    hull_mask = np.zeros(shape, dtype=bool)
    for tri in hull.simplices:
        p0, p1, p2 = wm_points[tri]

        # Sample points inside the triangle
        for i in range(oversample):
            for j in range(oversample - i):
                a = i / oversample
                b = j / oversample
                c = 1.0 - a - b
                point = a * p0 + b * p1 + c * p2
                voxel = tuple(np.round(point).astype(int))
                if all(0 <= voxel[d] < shape[d] for d in range(3)):
                    hull_mask[voxel] = True

    hull_mask = ndimage.binary_dilation(hull_mask, iterations=1).astype(bool)

    # Get distance map from hull surface
    depth_map = cast(
        np.ndarray, ndimage.distance_transform_edt(~hull_mask, sampling=spacing)
    )
    depth_map[~candidates_mask] = 0  # limit to candidate seeds

    # Compute laplacian to capture "minima", likely corresponding to
    # the "folding" (deepest) points of sulci
    laplacian = np.zeros_like(depth_map)
    for i, s in enumerate(spacing):
        # 1D spacing-aware second derivative along axis i
        deriv2 = cast(np.ndarray, ndimage.correlate1d(depth_map, [1, -2, 1], axis=i))
        laplacian += deriv2 / (s**2)

    # Smooth
    sigma = (1 / spacing[0], 1 / spacing[1], 1 / spacing[2])
    laplacian_smooth = ndimage.gaussian_filter(laplacian, sigma=sigma)
    depth_smooth = ndimage.gaussian_filter(depth_map, sigma=sigma)

    # Threshold
    depth_thresh = np.percentile(depth_smooth[candidates_mask], 95)
    laplacian_thresh = np.percentile(laplacian_smooth[candidates_mask], 1)

    # Combine lowest laplacian with maximum depth to get bottom of sulci mask
    return (depth_smooth > depth_thresh) & (laplacian_smooth < laplacian_thresh)


def _distance_based_growth(
    seed_point: tuple[int, int, int],
    lesion_mask: np.ndarray,
    spacing: tuple[_DistanceType, _DistanceType, _DistanceType],
    totals: dict[str, np.floating],
    gm_mask: np.ndarray,
    wm_mask: np.ndarray,
    gm_prob: float,
    target_volume: _DistanceType,
    noise_lambda: float,
    rng: np.random.RandomState | np.random.Generator,
) -> bool:
    """
    Lesion growth loop for distance-driven growth.

    Note:
        Modifies the input queues and lesion mask in place.
    """
    # Create heap queues for GM and WM
    gm_heap: list[tuple[float, int, int, int]] = (
        [(0.0, *seed_point)] if gm_mask[*seed_point] else []
    )
    wm_heap: list[tuple[float, int, int, int]] = (
        [(0.0, *seed_point)] if wm_mask[*seed_point] else []
    )
    visited: set[tuple[int, int, int]] = {seed_point}

    # Create GM-WM mask for anatomical constraint
    gm_wm_mask = gm_mask | wm_mask

    # Per-voxel contribution to physical volume
    vol_per_vox = np.prod(spacing)

    # Create smooth noise field for shape variability
    noise_field = generate_noise_field(
        shape=lesion_mask.shape,
        spacing=spacing,
        corr_sigma=1,
        random_state=rng,
    )

    while totals["curr_volume"] < target_volume:
        is_gm = rng.uniform() < gm_prob

        if (is_gm and gm_heap) or not wm_heap:
            active_heap = gm_heap
        else:
            active_heap = wm_heap

        if len(active_heap) == 0:
            return False

        # Pop the closest point from the active heap
        curr_dist, dim1, dim2, dim3 = heapq.heappop(active_heap)
        lesion_mask[dim1, dim2, dim3] = True
        totals["curr_volume"] += vol_per_vox
        if gm_mask[dim1, dim2, dim3]:
            totals["curr_gm_volume"] += vol_per_vox

        # Get neighbors and add to heap
        neighbors = [
            (d1, d2, d3)
            for d1 in (-1, 0, 1)
            for d2 in (-1, 0, 1)
            for d3 in (-1, 0, 1)
            if (d1, d2, d3) != (0, 0, 0)
        ]

        # Add noise to global distance
        curr_dist *= 1 + noise_lambda * noise_field[dim1, dim2, dim3]

        for d1, d2, d3 in neighbors:
            n1, n2, n3 = dim1 + d1, dim2 + d2, dim3 + d3
            if (
                0 <= n1 < lesion_mask.shape[0]
                and 0 <= n2 < lesion_mask.shape[1]
                and 0 <= n3 < lesion_mask.shape[2]
                and gm_wm_mask[n1, n2, n3]
                and (n1, n2, n3) not in visited
                and not lesion_mask[n1, n2, n3]
            ):
                dist = curr_dist + np.sqrt(
                    (d1 * spacing[0]) ** 2
                    + (d2 * spacing[1]) ** 2
                    + (d3 * spacing[2]) ** 2
                )
                if gm_mask[n1, n2, n3]:
                    heapq.heappush(gm_heap, (dist, n1, n2, n3))
                else:
                    heapq.heappush(wm_heap, (dist, n1, n2, n3))
                visited.add((n1, n2, n3))

    return True


def _irregular_growth(
    seed_point: tuple[int, int, int],
    lesion_mask: np.ndarray,
    spacing: tuple[_DistanceType, _DistanceType, _DistanceType],
    totals: dict[str, np.floating],
    gm_mask: np.ndarray,
    wm_mask: np.ndarray,
    gm_prob: float,
    target_volume: _DistanceType,
    fast_mode: bool,
    rng: np.random.RandomState | np.random.Generator,
) -> bool:
    """
    Lesion growth loop for irregular growth.

    Note:
        Modifies the input queues and lesion mask in place.
    """
    # Convert to isotropic space preserving finest resolution
    seed_iso = (
        round(seed_point[0] * spacing[0] / min(spacing)),
        round(seed_point[1] * spacing[1] / min(spacing)),
        round(seed_point[2] * spacing[2] / min(spacing)),
    )

    # Store <iso, voxel> pairs for each queue to avoid re-computing mappings each time
    gm_queue: list[tuple[tuple[int, int, int], tuple[int, int, int]]] = []  # iso, voxel
    wm_queue: list[tuple[tuple[int, int, int], tuple[int, int, int]]] = []
    visited_iso: set[tuple[int, int, int]] = {seed_iso}
    lesion_iso: set[tuple[int, int, int]] = set()
    if gm_mask[*seed_point]:
        gm_queue.append((seed_iso, seed_point))
    if wm_mask[*seed_point]:
        wm_queue.append((seed_iso, seed_point))

    # Create GM-WM mask for anatomical constraint
    gm_wm_mask = gm_mask | wm_mask

    # Per-voxel contribution to physical volume
    vol_per_vox = np.prod(spacing)

    while totals["curr_volume"] < target_volume:
        is_gm = rng.uniform() < gm_prob

        if (is_gm and gm_queue) or not wm_queue:
            active_queue = gm_queue
        else:
            active_queue = wm_queue

        if len(active_queue) == 0:
            return False

        # Pop a random point from the growing queue
        idx = rng.choice(len(active_queue))
        coords_iso, coords_vox = active_queue.pop(idx)
        lesion_iso.add(coords_iso)

        if fast_mode and lesion_mask[*coords_vox]:
            continue

        if not lesion_mask[*coords_vox]:
            lesion_mask[*coords_vox] = True
            totals["curr_volume"] += vol_per_vox
            if gm_mask[*coords_vox]:
                totals["curr_gm_volume"] += vol_per_vox

        # Randomly sample 2-5 neighboring voxels
        neighbors = [
            (d1 + coords_iso[0], d2 + coords_iso[1], d3 + coords_iso[2])
            for d1 in (-1, 0, 1)
            for d2 in (-1, 0, 1)
            for d3 in (-1, 0, 1)
            if (d1, d2, d3) != (0, 0, 0)
        ]
        idx = rng.choice(len(neighbors), size=2 + rng.choice(3), replace=False)

        # Add valid neighbors to the queues
        for neighbor in neighbors:
            vox = (
                round(neighbor[0] * min(spacing) / spacing[0]),
                round(neighbor[1] * min(spacing) / spacing[1]),
                round(neighbor[2] * min(spacing) / spacing[2]),
            )
            if (
                0 <= vox[0] < lesion_mask.shape[0]
                and 0 <= vox[1] < lesion_mask.shape[1]
                and 0 <= vox[2] < lesion_mask.shape[2]
                and gm_wm_mask[*vox]
                and neighbor not in visited_iso
                and (fast_mode or neighbor not in lesion_iso)
                and not (fast_mode and lesion_mask[*vox])
            ):
                if gm_mask[*vox]:
                    gm_queue.append((neighbor, vox))
                else:
                    wm_queue.append((neighbor, vox))
                visited_iso.add(neighbor)

    return True
